<a href="https://colab.research.google.com/github/2303A52504/23CSBTB50/blob/main/2303A52504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))
a=[1,2,3,4,5]
b=[5,4,3,2,1]
c=a+b
print(c)
c=np.array(c)
print(np.sort(c))
c=c.reshape(5,2)
print(c)
print(np.sort(c))
c=c.reshape(10,1)
print(c)
print(np.sort(c))
c=c.reshape(2,5)
print(c)
print(np.sort(c))
c=c.reshape(10,1)
print(c)
print(np.sort(c))



[0 1 2 3]
[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
[1 1 2 2 3 3 4 4 5 5]
[[1 2]
 [3 4]
 [5 5]
 [4 3]
 [2 1]]
[[1 2]
 [3 4]
 [5 5]
 [3 4]
 [1 2]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [5]
 [4]
 [3]
 [2]
 [1]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [5]
 [4]
 [3]
 [2]
 [1]]
[[1 2 3 4 5]
 [5 4 3 2 1]]
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [5]
 [4]
 [3]
 [2]
 [1]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [5]
 [4]
 [3]
 [2]
 [1]]
